# Generated by Django 4.1 on 2022-09-08 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auxiliares',
            fields=[
                ('docu_auxi', models.IntegerField(primary_key='docu_auxi', serialize=False)),
                ('genero', models.CharField(max_length=12)),
                ('prim_nomb_auxi', models.CharField(max_length=20)),
                ('segu_nomb_auxi', models.CharField(max_length=20)),
                ('prim_apel_auxi', models.CharField(max_length=20)),
                ('segu_apel_auxi', models.CharField(max_length=20)),
                ('usuario_auxi', models.CharField(max_length=30)),
                ('contrasena_auxi', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='enfermeros',
            fields=[
                ('docu_enfer', models.IntegerField(primary_key='docu_enfer', serialize=False)),
                ('genero', models.CharField(max_length=12)),
                ('prim_nomb_enfer', models.CharField(max_length=20)),
                ('segu_nomb_enfer', models.CharField(max_length=20)),
                ('prim_apel_enfer', models.CharField(max_length=20)),
                ('segu_apel_enfer', models.CharField(max_length=20)),
                ('usuario_enfer', models.CharField(max_length=30)),
                ('contrasena_enfer', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='familiares',
            fields=[
                ('docu_fami', models.IntegerField(primary_key='docu_fami', serialize=False)),
                ('genero', models.CharField(max_length=12)),
                ('prim_nomb_fami', models.CharField(max_length=20)),
                ('segu_nomb_fami', models.CharField(max_length=20)),
                ('prim_apel_fami', models.CharField(max_length=20)),
                ('segu_apel_fami', models.CharField(max_length=20)),
                ('tel_fami', models.IntegerField()),
                ('dir_fami', models.CharField(max_length=30)),
                ('corr_fami', models.CharField(max_length=30)),
                ('usuario_fami', models.CharField(max_length=30)),
                ('contrasena_fami', models.CharField(max_length=12)),
                ('parentesco', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='medicos',
            fields=[
                ('docu_medi', models.IntegerField(primary_key='docu_medi', serialize=False)),
                ('genero', models.CharField(max_length=12)),
                ('prim_nomb_medi', models.CharField(max_length=20)),
                ('segu_nomb_medi', models.CharField(max_length=20)),
                ('prim_apel_medi', models.CharField(max_length=20)),
                ('segu_apel_medi', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=25)),
                ('regist_medi', models.CharField(max_length=15)),
                ('usuario_med', models.CharField(max_length=30)),
                ('contrasena_med', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('docu_paci', models.IntegerField(primary_key='docu_paci', serialize=False)),
                ('genero', models.CharField(max_length=12)),
                ('fech_naci_paci', models.DateField()),
                ('prim_nomb_paci', models.CharField(max_length=20)),
                ('segu_nomb_paci', models.CharField(max_length=20)),
                ('prim_apel_paci', models.CharField(max_length=20)),
                ('segu_apel_paci', models.CharField(max_length=20)),
                ('ubic_paci', models.CharField(max_length=20)),
                ('direc_paci', models.CharField(max_length=30)),
                ('ciudad_paci', models.CharField(max_length=30)),
                ('tele_paci', models.IntegerField()),
                ('usuario_paci', models.CharField(max_length=30)),
                ('contrasena_paci', models.CharField(max_length=12)),
                ('docu_enfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sprint2.enfermeros')),
                ('docu_fami', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sprint2.familiares')),
                ('docu_medi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sprint2.medicos')),
            ],
        ),
        migrations.CreateModel(
            name='signos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('oximetria', models.IntegerField()),
                ('frec_resp', models.IntegerField()),
                ('frec_card', models.IntegerField()),
                ('temperatura', models.IntegerField()),
                ('pre_arte', models.CharField(max_length=8)),
                ('glucem', models.IntegerField()),
                ('fecha', models.DateField()),
                ('diag_paci', models.CharField(max_length=30)),
                ('suge_cuidado', models.CharField(max_length=100)),
                ('docu_paci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sprint2.pacientes')),
            ],
        ),
        migrations.AddField(
            model_name='familiares',
            name='docu_paci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sprint2.pacientes'),
        ),
    ]
